FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc g++ build-essential libopenblas-dev && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir numpy==2.2.6
RUN pip install --no-cache-dir --no-build-isolation -r requirements.txt
COPY . .
CMD ["streamlit","run","src/dashboard/app.py","--server.port=8501", "--server.address=0.0.0.0"]


